### PR TITLE
Update a few things

### PR DESCRIPTION
**Pull request by guizmaii**
- Update Scala version
- Update sbt
- Remove now useless sbt-dotty plugin. For more information, see https://eed3si9n.com/sbt-1.5.0
- Update some dependencies
- Update sbt syntax

### CODE REVIEW

**Comment by dimafeng** [comment]
Hey @guizmaii, thanks! Seems the build got broken - would you mind looking into it?

**Comment by guizmaii** [comment]
```java
[pool-1-thread-1] INFO 🐳 [oracleinanutshell/oracle-xe-11g:latest] - Container oracleinanutshell/oracle-xe-11g:latest is starting: d387e14ac859680f9e17b01a8a89de967d812fe9f810bfa589fdde64f5b6779b
[pool-1-thread-1] INFO 🐳 [oracleinanutshell/oracle-xe-11g:latest] - Waiting for database connection to become available at jdbc:oracle:thin:system/oracle@localhost:49166:xe using query 'SELECT 1 FROM DUAL'
[pool-1-thread-1] ERROR 🐳 [oracleinanutshell/oracle-xe-11g:latest] - Could not start container
java.lang.IllegalStateException: Container is started, but cannot be accessed by (JDBC URL: jdbc:oracle:thin:system/oracle@localhost:49166:xe), please check container logs
	at org.testcontainers.containers.JdbcDatabaseContainer.waitUntilContainerStarted(JdbcDatabaseContainer.java:165)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:466)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:329)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:327)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:315)
	at com.dimafeng.testcontainers.SingleContainer.start(Container.scala:46)
	at com.dimafeng.testcontainers.ForAllTestContainer$class.run(ForAllTestContainer.scala:17)
	at com.dimafeng.testcontainers.OracleSpec.run(OracleSpec.scala:7)
	at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:318)
	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:486)
	at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:413)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
[pool-1-thread-1] ERROR 🐳 [oracleinanutshell/oracle-xe-11g:latest] - Log output from the failed container:
```

Looks like an intermittent error. Can you relaunch the tests please, @dimafeng?

**Comment by dimafeng** [comment]
@guizmaii seems it's still failing

**Comment by guizmaii** [comment]
Could these changes be related/could improve the situation for us here: https://github.com/testcontainers/testcontainers-java/pull/4402? 🤔

**Comment by guizmaii** [comment]
@dimafeng I update the Oracle driver to see if it changes something 🤷. Can you relaunch the tests, please?

**Comment by dimafeng** [comment]
Hm, still failing. Let me try to create a branch and see if master is still passing all tests.

**Comment by guizmaii** [comment]
@dimafeng Is master still ok?

**Comment by dimafeng** [comment]
Sorry, it just finished - https://github.com/testcontainers/testcontainers-scala/pull/191 it seems ok

**Comment by guizmaii** [comment]
Weird! Thanks. I'll try a few things to try to fix that.

**Comment by guizmaii** [comment]
@dimafeng I fixed the tests. The problem comes from testcontainers 1.16.0 as you can see here: https://github.com/testcontainers/testcontainers-scala/pull/193

**Pull request merged**
