### PR TITLE
Add alias for creating a generic container definition

### PR DESCRIPTION
**Pull request by alejandrohdezma**
Just adds an alias for creating a `ContainerDef` for a `GenericContainer` that doesn't involve creating a new object/class.

Example:

```scala
import scala.io.Source

import java.net.URL

import org.scalatest.flatspec.AnyFlatSpec

import com.dimafeng.testcontainers.GenericContainer
import com.dimafeng.testcontainers.scalatest.TestContainerForAll

import org.testcontainers.containers.wait.strategy.Wait

class GenericContainerSpec extends AnyFlatSpec with TestContainerForAll {
  
  override val containerDef = GenericContainer.Def.anonymous("nginx:latest",
    exposedPorts = Seq(80),
    waitStrategy = Wait.forHttp("/")
  )

  "GenericContainer" should "start nginx and expose 80 port" in withContainers { container =>
    assert(Source.fromInputStream(
      new URL(s"http://${container.containerIpAddress}::${container.mappedPort(80)}/").openConnection().getInputStream
    ).mkString.contains("If you see this page, the nginx web server is successfully installed"))
  }

}
```

### CODE REVIEW

**Comment by LMnet** [comment]
Hi @alejandrohdezma

I tried to compile your example but it's not compiling. Could you fix it? After that, we will be able to discuss your idea in more detail.

**Comment by alejandrohdezma** [comment]
Thanks @LMnet, I have updated the example and the changes. The example was using the wrong trait and missing the `withContainers`. I've also updated the changes since previous changes didn't allow the suite to use the container as a `GenericContainer` and thus unable to use methods like `mappedPort`, should be fixed now.

**Comment by alejandrohdezma** [comment]
@LMnet done!

**Review by LMnet — APPROVED** [review]

**Comment by dimafeng** [comment]
@alejandrohdezma would you mind updating your example snippet. It seems I'm not following the idea with `anonymous` but an example should help

**Comment by alejandrohdezma** [comment]
Done!

**Comment by dimafeng** [comment]
Hey @LMnet quick question - why `GenericContainer.Def.anonymous` is better than just `GenericContainer.Def`? I think I'm missing something.

**Comment by LMnet** [comment]
All my concerns I described [above](https://github.com/testcontainers/testcontainers-scala/pull/194#issuecomment-937465336). The default use case for `GenericContainer.Def` is described [here](https://github.com/testcontainers/testcontainers-scala#genericcontainer-usage).

Overall, `GenericContainer.Def` is a building block for a container definition for some container. But @alejandrohdezma's use case is about creating an anonymous container definition (means without corresponding class for a container).

If we will use `apply` instead of `anonymous`, I think users may misuse this API. They could think that this `apply` is just an another form of a default constructor, but it's not actually true.

**Comment by alejandrohdezma** [comment]
> Got it! It makes sense.
> 
> @LMnet @alejandrohdezma would it make sense to create a new class instead e.g.`AnonymousGenericContainer` / `AnonymousContainer`? In that case, it's going to be a bit more consistent with other `Def`'s (`override val containerDef = AnonymousGenericContainer.Def(...)`) What do you think?

Of course! I'll send a new commit tomorrow morning :(

**Comment by dimafeng** [comment]
Thanks!

@LMnet does it sounds good to you?

**Comment by dimafeng** [comment]
Seems we're comparing several non-ideal solutions:
- `GenericContainer.Def.anonymous` goes against the convention that all other `Def`s use
- `AnonymousGenericContainer.Def` breaks the 1:1 mapping with old api
- `GenericContainer.Def` uses `apply` non-canonically 

4th option: 
Should we consider renaming `abstract class Def[C <: GenericContainer]` to something else and then reusing it for a definition of `GenericContainer.Def`?

**Comment by alejandrohdezma** [comment]
Sorry @dimafeng I didn't see your reply :(

What I like about the `apply` idea is that it doesn't involve a breaking change (like renaming `Def`) and it is consistent with all the other containers, where you have `PostgresContainer.Def#apply`, but in this case for creating a "generic" one.

**Comment by dimafeng** [comment]
After thinking a bit, I'm leaning toward your options with `Def.apply` with potential breaking-change migration to the option 4 in the future. For me, consistency is pretty important for discoverability. 

@LMnet any final thoughts?

**Comment by alejandrohdezma** [comment]
Of course, I'll do it as soon as possible :)

**Comment by alejandrohdezma** [comment]
> @alejandrohdezma can we proceed with the option 3? Would you mind also changing README and adding a simple test?

Done! :)

**Comment by alejandrohdezma** [comment]
@dimafeng should be fixed now

**Pull request merged**
