### PR TITLE
upgrade to scalatest 3.2.3

### PR DESCRIPTION
**Pull request by sullis**

### CODE REVIEW

**Comment by sullis** [comment]
@dimafeng  WDYT?

**Comment by dimafeng** [comment]
@sullis sorry, I missed this one. I'll take a look today.

**Comment by dimafeng** [comment]
@LMnet - what do you think about this PR? I was about to release a new version with this and then started thinking about ways to simplify the upgrade for the users. After upgrading to 0.38.9, users will get a conflict in dependencies with `scalatest 3.2.*`, I guess some will be ok to upgrade but I bet for some it's going to be a problem. They could force `3.0.*` in their dependencies because `testcontainers-scala-scalatest` is code-compatible. A problem comes with `testcontainers-scala-scalatest-selenium` since it's using classes with new names.

I see two options:
1.  Release as-is and force users to solve this issue on their own
2. Create two more modules for `scalatest 3.2.*` and leave `testcontainers-scala-scalatest/testcontainers-scala-scalatest-selenium` the way it was

Of course, option 1 is easier and cleaner at the end of the day

**Comment by LMnet** [comment]
I think we should release as-is, but as 0.39.0. And mention this change in the readme.

Creating multiple modules will add additional maintenance costs and add a bit of confusion for users.

**Pull request merged**
