### PR TITLE
Fix build

### PR DESCRIPTION
**Pull request by LMnet**
After the last update of the sbt import to the Intellij Idea is not working. It failed with an error:
```
sbt:root> last microsite/ivyConfiguration
[error] insecure HTTP request is unsupported 'http://dl.bintray.com/tpolecat/maven'; switch to HTTPS or opt-in as ("tpolecat" at "http://dl.bintray.com/tpolecat/maven").withAllowInsecureProtocol(true), or by using allowInsecureProtocol in repositories file
[error] java.lang.RuntimeException: insecure protocol is unsupported
[error]         at scala.sys.package$.error(package.scala:30)
[error]         at sbt.Classpaths$.errorInsecureProtocol(Defaults.scala:3116)
[error]         at sbt.Classpaths$.$anonfun$mkIvyConfiguration$1(Defaults.scala:3712)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error]         at sbt.Execute.work(Execute.scala:291)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (microsite / ivyConfiguration) insecure protocol is unsupported
```
Looks like Idea's importer tries to resolve all dependencies and saw http dependency without `withAllowInsecureProtocol(true)` in sbt-microsite plugin code.

To fix this issue I updated sbt-microsite to the latest version. I didn't do any migration steps, I just bumped version and removed unsupported stuff to make idea import works again. Fixing of documentation will need an extra pull request.

### CODE REVIEW

**Comment by dimafeng** [comment]
@LMnet perhaps we can remove the site generation completely since it's not used anyways

**Comment by LMnet** [comment]
@dimafeng I thought you are doing something with docs in some branch. If not, what exactly you mean? Remove the whole docs module or only sbt-microsite plugin?

**Comment by dimafeng** [comment]
@LMnet I paused it after comments from @rnorth regarding the site engine. At this point, both options work - drop the whole docs module or sbt-microsite plugin only. When I get back to docs, I'll need to start over in any case.

**Comment by dimafeng** [comment]
@LMnet closing this due to https://github.com/testcontainers/testcontainers-scala/pull/157

**Pull request closed without merging**
