### PR TITLE
upgrading to Scala 3 to RC1

### PR DESCRIPTION
**Pull request by BusyByte**

### CODE REVIEW

**Comment by dimafeng** [comment]
@BusyByte thank you for your PR! I see that the build has failed, could you please take a look into this?

**Comment by BusyByte** [comment]
@dimafeng looks like some dependencies have not upgraded to RC1 yet:
```
[error] sbt.librarymanagement.ResolveException: Error downloading org.scalatestplus:selenium-3-141_3.0.0-RC1:3.2.3.0
[error]   Not found
[error]   Not found
[error]   not found: /home/runner/.ivy2/localorg.scalatestplus/selenium-3-141_3.0.0-RC1/3.2.3.0/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/scalatestplus/selenium-3-141_3.0.0-RC1/3.2.3.0/selenium-3-141_3.0.0-RC1-3.2.3.0.pom
[error]   not found: https://jcenter.bintray.com/org/scalatestplus/selenium-3-141_3.0.0-RC1/3.2.3.0/selenium-3-141_3.0.0-RC1-3.2.3.0.pom
[error] Error downloading org.scalatestplus:mockito-3-4_3.0.0-RC1:3.2.3.0
[error]   Not found
[error]   Not found
[error]   not found: /home/runner/.ivy2/localorg.scalatestplus/mockito-3-4_3.0.0-RC1/3.2.3.0/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/scalatestplus/mockito-3-4_3.0.0-RC1/3.2.3.0/mockito-3-4_3.0.0-RC1-3.2.3.0.pom
[error]   not found: https://jcenter.bintray.com/org/scalatestplus/mockito-3-4_3.0.0-RC1/3.2.3.0/mockito-3-4_3.0.0-RC1-3.2.3.0.pom
[error] Error downloading org.scalatest:scalatest_3.0.0-RC1:3.2.3
[error]   Not found
[error]   Not found
[error]   not found: /home/runner/.ivy2/localorg.scalatest/scalatest_3.0.0-RC1/3.2.3/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/scalatest/scalatest_3.0.0-RC1/3.2.3/scalatest_3.0.0-RC1-3.2.3.pom
[error]   not found: https://jcenter.bintray.com/org/scalatest/scalatest_3.0.0-RC1/3.2.3/scalatest_3.0.0-RC1-3.2.3.pom
[error] 	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:258)
[error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$38(CoursierDependencyResolution.scala:227)
[error] 	at scala.util.Either$LeftProjection.map(Either.scala:573)
[error] 	at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:227)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:53)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:103)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:73)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:116)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:116)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:97)
[error] 	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:130)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$5(Defaults.scala:3486)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (core / update) sbt.librarymanagement.ResolveException: Error downloading org.scalatestplus:selenium-3-141_3.0.0-RC1:3.2.3.0
[error]   Not found
[error]   Not found
[error]   not found: /home/runner/.ivy2/localorg.scalatestplus/selenium-3-141_3.0.0-RC1/3.2.3.0/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/scalatestplus/selenium-3-141_3.0.0-RC1/3.2.3.0/selenium-3-141_3.0.0-RC1-3.2.3.0.pom
[error]   not found: https://jcenter.bintray.com/org/scalatestplus/selenium-3-141_3.0.0-RC1/3.2.3.0/selenium-3-141_3.0.0-RC1-3.2.3.0.pom
[error] Error downloading org.scalatestplus:mockito-3-4_3.0.0-RC1:3.2.3.0
[error]   Not found
[error]   Not found
[error]   not found: /home/runner/.ivy2/localorg.scalatestplus/mockito-3-4_3.0.0-RC1/3.2.3.0/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/scalatestplus/mockito-3-4_3.0.0-RC1/3.2.3.0/mockito-3-4_3.0.0-RC1-3.2.3.0.pom
[error]   not found: https://jcenter.bintray.com/org/scalatestplus/mockito-3-4_3.0.0-RC1/3.2.3.0/mockito-3-4_3.0.0-RC1-3.2.3.0.pom
[error] Error downloading org.scalatest:scalatest_3.0.0-RC1:3.2.3
[error]   Not found
[error]   Not found
[error]   not found: /home/runner/.ivy2/localorg.scalatest/scalatest_3.0.0-RC1/3.2.3/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/scalatest/scalatest_3.0.0-RC1/3.2.3/scalatest_3.0.0-RC1-3.2.3.pom
[error]   not found: https://jcenter.bintray.com/org/scalatest/scalatest_3.0.0-RC1/3.2.3/scalatest_3.0.0-RC1-3.2.3.pom
[error] Total time: 5 s, completed Feb 22, 2021 1:42:51 AM

Error: Process completed with exit code 1.
```

I'm not sure how to fix this except for wait for these dependencies to upgrade to RC1 as well.

**Comment by BusyByte** [comment]
@dimafeng I see they have another version which depends on RC1, changed in 35c463a

**Comment by BusyByte** [comment]
@dimafeng scalatestplus does not seem to have a release for RC1 that I can find

**Comment by BusyByte** [comment]
@dimafeng looks like maybe the artifact name changed for selenium: `libraryDependencies += "org.scalatestplus" %% "selenium-3-141" % "3.2.5.0"` has a release for RC1

**Comment by BusyByte** [comment]
@dimafeng bumped scalatest selenium version in 73d1103

**Comment by BusyByte** [comment]
@dimafeng finally found the scalatest plus mockito dependency needed, updated in 1d5e091

One thing that was really confusing is the last updated dates on the https://mvnrepository.com/artifact/org.scalatestplus?p=1 were not right as there were newer releases once you click on an artifact.

**Comment by BusyByte** [comment]
@dimafeng looks like only munit is left, I'll look at that one later tonight:
`https://repo1.maven.org/maven2/org/scalameta/munit_3.0.0-RC1/0.7.21/munit_3.0.0-RC1-0.7.21.pom`

**Comment by BusyByte** [comment]
@dimafeng munit version bumped in 9d8f2ff

**Comment by BusyByte** [comment]
@dimafeng looks like this PR is green now

**Comment by dimafeng** [comment]
@BusyByte great! Thank you!

**Pull request merged**
