### PR TITLE
Update testContainer Version to 1.8.2

### PR DESCRIPTION
**Pull request by mrtnrdl**
I started to work on this, because it fixes my problem with the private Google Container Registry. 

I'm not sure how to proceed, because on my machine, one of the test suites fails with 
````
com.dimafeng.testcontainers.integration.SeleniumSpec *** ABORTED ***
[info]   java.io.IOException: Error detected parsing the header
[info]   at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.getNextTarEntry(TarArchiveInputStream.java:285)
(...)
[info]   ...
[info]   Cause: java.lang.IllegalArgumentException: Invalid byte 15 at offset 0 in '����/' len=8
[info]   at org.apache.commons.compress.archivers.tar.TarUtils.parseOctal(TarUtils.java:141)
(...)
````

On master, I have four failing suites, so I don't exactly know how I could solve this. I'd be happy to help, but I guess I need some guidance.
 
I'm already on docker client version 18.06.0-ce-mac70 on macOs High Sierra 10.13.6

### CODE REVIEW

**Comment by mrtnrdl** [comment]
Yay, travis verified that for me \o/

**Comment by dimafeng** [comment]
@mrtnrdl thank you for the PR! It looks like a valid change anyways, so I'm going to merge it and play locally.

**Comment by dimafeng** [comment]
@mrtnrdl if everything is good, I'll release a new version later today.

**Comment by dimafeng** [comment]
@mrtnrdl I have the same problem with tests locally. I'm still trying to figure out what the root cause is.

**Comment by rnorth** [comment]
Is it a tar error running locally? There’s another serious regression with docker 18.06 that breaks copy operations. 

We’re going to have to tackle, but for now the OkHttp transport works (netty is affected). OkHttp transport is opt in, but I think we’ll have to do another release to make it the default. 

I’ll raise a ticket with the details, but for now please don’t worry about the local failure. We’ll try and have the workaround out ASAP.

Richard

**Comment by mrtnrdl** [comment]
I have to check again. I'm currently afk, but I can verify it tomorrow.

**Comment by mrtnrdl** [comment]
@rnorth at least for me it was the tar-error.

**Comment by dimafeng** [comment]
@mrtnrdl everything should be fixed in 0.20.0, please try

**Comment by mrtnrdl** [comment]
@dimafeng works like a charm! Thanks mate :)

**Pull request merged**
