### PR TITLE
Add schema registry container

### LINKED ISSUE #182: how can I create a Schema Registry test container and connect it to a Kafka test container?

### PR DESCRIPTION
**Pull request by AdrianRaFo**
Fixes #182

Thanks to @mikhailchuryakov from who I got the base for this

### CODE REVIEW

**Comment by AdrianRaFo** [comment]
@dimafeng not sure what kind of tests should I add here. Could you guide me on that?

**Comment by dimafeng** [comment]
@AdrianRaFo I'm not an expert in Kafka so I'm not really sure how to properly test it. I'd consult with @mikhailchuryakov, I see that he has this test in his example
https://github.com/mikhailchuryakov/schema-registry-testcontainers/blob/master/src/test/scala/example/kafka/SchemaRegistryTest.scala

**Comment by AdrianRaFo** [comment]
Thanks, I will do a test combining both containers so it also works as an example

**Comment by dimafeng** [comment]
@mikhailchuryakov would you mind reviewing this PR if you have a chance? I'm afraid I don't have enough knowledge about kafka to codereview this.

**Pull request merged**
