### PR TITLE
Scala 3.0.0

### PR DESCRIPTION
**Pull request by tpolecat**
This updates testcontainers to Scala ~~3.0.0-RC3~~ 3.0.0.

### CODE REVIEW

**Comment by tpolecat** [comment]
There is a connection link failure that may be a timing issue. Re-run maybe?

**Comment by dimafeng** [comment]
Looks like it. Re-running...

**Comment by tpolecat** [comment]
Sorry, I committed a metals file. Deleted.

**Comment by dimafeng** [comment]
Hm, still failing with mysql test. I'll take a look over this week.

**Comment by dimafeng** [comment]
@tpolecat I suspect https://github.com/testcontainers/testcontainers-scala/pull/178 should help. Can't reproduce this error locally.

**Comment by dimafeng** [comment]
Turns out it's related to this https://github.com/testcontainers/testcontainers-java/issues/4058

**Comment by dimafeng** [comment]
@tpolecat I merged the fix for mysql spec to master. Would you mind merging it to your branch?

**Comment by tpolecat** [comment]
Ok I rebased.

**Comment by dimafeng** [comment]
@tpolecat thanks! now it's failing with:
```
Uncaught exception when running com.dimafeng.testcontainers.integration.GenericContainerDockerFileSpec: java.lang.NoSuchMethodError: 'org.testcontainers.images.builder.traits.BuildContextBuilderTrait org.testcontainers.images.builder.ImageFromDockerfile.withFileFromClasspath(java.lang.String, java.lang.String)'
``` 
Do you think it's related to your change or it's new flakiness?

**Comment by tpolecat** [comment]
Went ahead and upgraded to 3.0.0

**Comment by dimafeng** [comment]
Hm, still the same error. I'm still trying to figure out why it's failing.

**Comment by milessabin** [comment]
Anything we can do to help?

**Comment by dimafeng** [comment]
Hi @milessabin, sorry, it has been a busy week and I haven't had a chance to take a look.
I'd appreciate any help with figuring out of the root cause of NoSuchMethodError.

**Comment by tpolecat** [comment]
I'm going to dig into this today and see what I can figure out.

**Comment by tpolecat** [comment]
I narrowed it down to what I think is a compiler bug, here https://github.com/lampepfl/dotty/issues/12586. I will write a Java stop to work around it for now.

**Pull request merged**
