### PR TITLE
Update test containers version

### PR DESCRIPTION
**Pull request by jaapterwoerds**
See https://github.com/testcontainers/testcontainers-java/issues/3574. Fixes issues with missing ryuk docker image.

### CODE REVIEW

**Comment by mdotson** [comment]
@dimafeng is it possible to get a release cut with this change soon?

**Comment by dimafeng** [comment]
@mdotson it was released yesterday - 0.38.8. Sorry I haven't had a chance to update the release notes.

**Comment by mdotson** [comment]
@dimafeng You're awesome! Thank you!

**Comment by jaapterwoerds** [comment]
👌

Op vr 18 dec. 2020 18:50 schreef Michael Dotson <notifications@github.com>:

**Pull request merged**
